import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'
import './globals.css'
import type { Metadata } from 'next'
import ThemeRegistry from './_layout/theme/ThemeRegistry'
import ListItem from '@mui/material/ListItem';
import ListItemIcon from '@mui/material/ListItemIcon'
import ListItemText from '@mui/material/ListItemText'
import ListItemButton from '@mui/material/ListItemButton'
import StorefrontOutlinedIcon from '@mui/icons-material/StorefrontOutlined';
import CalculateOutlinedIcon from '@mui/icons-material/CalculateOutlined';
import FoodBankOutlinedIcon from '@mui/icons-material/FoodBankOutlined';
import HistoryEduOutlinedIcon from '@mui/icons-material/HistoryEduOutlined';
import Navbar from './_layout/Navbar';
import LocalizationProvider from './_layout/LocalizationProvider';
import Link from 'next/link';
import { Suspense } from 'react';
import { Loading } from './_components/Loading';
import { SxProps, Theme } from '@mui/material/styles'
import List from '@mui/material/List'
import NavbarLink from './_layout/NavbarLink'


export const metadata: Metadata = {
  title: '我是貓咪!!!',
  description: 'Generated by create next app',
}

export const menus = [
  {
    name: '飲食紀錄',
    path: '/record',
    Icon: HistoryEduOutlinedIcon
  },
  {
    name: '收藏食物',
    path: '/food',
    Icon: FoodBankOutlinedIcon
  },
  {
    name: '品牌一覽',
    path: '/brand',
    Icon: StorefrontOutlinedIcon
  },
  {
    name: '成分計算',
    path: '/calculator',
    Icon: CalculateOutlinedIcon
  },
]

const listStyle: SxProps<Theme> = {
    '.MuiListItem-root': {
      justifyContent: 'center'
    },
    '.MuiListItemButton-root': {
      borderRadius: '100px',
      px: 1,
      justifyContent: 'center'
    },
    '.MuiListItemIcon-root': {
      minWidth: 'auto',
      color: '#b8b4ae'
    },
}

export default function RootLayout({children,}:{children: React.ReactNode}) {

  return (
    <html lang="zh-tw">
      <body>
        <ThemeRegistry options={{ key: 'few' }}>
          <LocalizationProvider>
            <div className="flex">
              <Navbar>
                <List sx={listStyle}>
                {menus.map((menu) => (
                  <ListItem key={menu.path}>
                    <NavbarLink href={menu.path}>
                      <ListItemButton>
                        <ListItemIcon>
                          <menu.Icon/>
                        </ListItemIcon>
                        <ListItemText
                          primary={menu.name}
                          primaryTypographyProps={{
                            fontSize: '0.875rem',
                            fontWeight: 'bold',
                          }}
                          className="drawer-text ml-3" />
                      </ListItemButton>
                    </NavbarLink>
                  </ListItem>
                ))}
                </List>
              </Navbar>
              <div className="flex-grow">
                <Suspense fallback={<Loading/>}>
                  {children}
                </Suspense>
              </div>
            </div>
          </LocalizationProvider>
        </ThemeRegistry>
      </body>
    </html>
  )
}
