import './globals.css'
import type { Metadata } from 'next'
import ThemeRegistry from './_theme/ThemeRegistry'
import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemIcon from '@mui/material/ListItemIcon'
import ListItemText from '@mui/material/ListItemText'
import ListItemButton from '@mui/material/ListItemButton'
import { BuildingStorefrontIcon, CalculatorIcon, CalendarIcon, ListBulletIcon } from '@heroicons/react/24/outline';
import { Drawer } from './_components/Drawer';
import Link from 'next/link';
import { Suspense } from 'react';
import { Loading } from './_components';


export const metadata: Metadata = {
  title: '我是貓咪!!!',
  description: 'Generated by create next app',
}

export const menus = [
  {
    name: '飲食紀錄',
    path: '/record',
    Icon: CalendarIcon
  },
  {
    name: '食物一覽',
    path: '/food',
    Icon: ListBulletIcon
  },
  {
    name: '品牌一覽',
    path: '/brand',
    Icon: BuildingStorefrontIcon
  },
  {
    name: '計算機',
    path: '/calculator',
    Icon: CalculatorIcon
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactElement
  }) {

  return (
    <html lang="zh-tw">
      <body>
        <ThemeRegistry options={{ key: 'few' }}>
          <div className="flex">
            <Drawer variant="permanent">
              <List>
                {menus.map((menu) => (
                  <ListItem key={menu.path} className='block'>
                    <Link href={menu.path}>
                      <ListItemButton className='justify-center px-3'>
                        <ListItemIcon className='mr-3 justify-center' sx={{minWidth: 'auto'}}>
                          <menu.Icon className='w-5 h-5'/>
                        </ListItemIcon>
                        <ListItemText primary={menu.name} className="drawer-text"/>
                      </ListItemButton>
                    </Link>
                  </ListItem>
                ))}
              </List>
            </Drawer>
            <div className="flex-grow">
              <Suspense fallback={<Loading/>}>
                {children}
              </Suspense>
            </div>
          </div>
        </ThemeRegistry>
      </body>
    </html>
  )
}
